### ISSUE TITLE
make toolbar to responsive ui

### ISSUE THREAD

**Issue by tak-bro** [naver-d2-suji/suji#17]

**Comment by tak-bro** [comment]
ref : http://blog.sodhanalibrary.com/2015/08/responsive-web-design-using-angularjs.html#.VtZ4Ffl96Uk

**Comment by njir** [comment]
ref : http://blog.sodhanalibrary.com/2015/08/responsive-web-design-using-angularjs.html#.VtZ4Ffl96Uk

**Comment by tak-bro** [comment]
```
<md-content flex>
  <ui-view layout="column" layout-fill layout-padding>
  </ui-view>
</md-content flex>
```

  </div>
</body>

index.html has to be fixed

**Comment by tak-bro** [comment]
finish
