### ISSUE TITLE
Pos's checkout not operate on mobile

### ISSUE THREAD

**Issue by tak-bro** [naver-d2-suji/suji#18]
what the f

**Comment by tak-bro** [comment]
temporary fix
have to chage date format

**Comment by tak-bro** [comment]
Assigned to BoWoon
because he is the development specialist.

**Comment by KimBoWoon** [comment]
수정완료
하지만 판매기록에서 똑같은 기록을 두 번 읽어들임

**Comment by tak-bro** [comment]
This issue closed
Open issue #19
