### ISSUE TITLE
Upload gif

### ISSUE THREAD

**Issue by tak-bro** [naver-d2-suji/suji#26]
![suji_thumbnail](https://cloud.githubusercontent.com/assets/7614353/13844696/bd2fed46-ec7e-11e5-867b-28d4e4931de2.gif)

**Comment by njir** [comment]
![logo](https://cloud.githubusercontent.com/assets/7614353/13726464/f724d79e-e90b-11e5-8146-0c749da4c4e7.jpg)

**Comment by tak-bro** [comment]
not used

**Comment by njir** [comment]
![video](https://cloud.githubusercontent.com/assets/7614353/13727892/3555f4b2-e948-11e5-9180-b68ea25b00df.PNG)

**Comment by njir** [comment]
![suji_logo](https://cloud.githubusercontent.com/assets/7614353/13728932/531fbed8-e96b-11e5-97a4-d8cc3ca12f4f.jpeg)

**Comment by njir** [comment]
![logo](https://cloud.githubusercontent.com/assets/7614353/13728987/bd47efaa-e96c-11e5-8856-58d38cca1088.jpeg)

**Comment by tak-bro** [comment]
![50logo](https://cloud.githubusercontent.com/assets/7614353/13728999/0374c7aa-e96d-11e5-85e8-ca3b2bb7b5b3.jpeg)

**Comment by tak-bro** [comment]
![image](https://cloud.githubusercontent.com/assets/7614353/13729008/4fe94b6a-e96d-11e5-8fbd-e2b886f5b98d.png)

**Comment by tak-bro** [comment]
![qrcode](https://cloud.githubusercontent.com/assets/7614353/13811187/7af95042-ebb7-11e5-9f4f-6ad3641df999.jpg)
