### ISSUE TITLE
Modify Query to create PRODUCT table

### ISSUE THREAD

**Issue by njir** [naver-d2-suji/suji#9]
Error 'SNO'

**Comment by KimBoWoon** [comment]
CREATE TABLE PRODUCT (
    NAME VARCHAR(100) NOT NULL,
    PRICE INT NOT NULL,
    COST INT NOT NULL,
    TAX TINYINT(1) NOT NULL,
    BARCODE VARCHAR(150) DEFAULT NULL,
    CATEGORYPK VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(NAME),
    FOREIGN KEY(CATEGORYPK) REFERENCES CATEGORY(NAME)
        ON DELETE SET NULL
        ON UPDATE CASCADE);

**Comment by njir** [comment]
Good
